// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7UQlnwcvSXFfSZemVWINdTkuqmeGUi8E',
    appId: '1:113425200543:web:cd1008dc81a51bf650b9aa',
    messagingSenderId: '113425200543',
    projectId: 'pamidoro-app',
    authDomain: 'pamidoro-app.firebaseapp.com',
    storageBucket: 'pamidoro-app.firebasestorage.app',
    measurementId: 'G-1GTSNWTC8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsnn0cpd4B99sxTA7vhS55SHt9yP5IgPg',
    appId: '1:113425200543:android:5a8c2c9a151e979550b9aa',
    messagingSenderId: '113425200543',
    projectId: 'pamidoro-app',
    storageBucket: 'pamidoro-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5jICUjsBVc3OzRMfT0MzB8J79EaCsMNY',
    appId: '1:113425200543:ios:4b821093b802e3cd50b9aa',
    messagingSenderId: '113425200543',
    projectId: 'pamidoro-app',
    storageBucket: 'pamidoro-app.firebasestorage.app',
    iosBundleId: 'com.pamidoro.pamidoro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5jICUjsBVc3OzRMfT0MzB8J79EaCsMNY',
    appId: '1:113425200543:ios:4b821093b802e3cd50b9aa',
    messagingSenderId: '113425200543',
    projectId: 'pamidoro-app',
    storageBucket: 'pamidoro-app.firebasestorage.app',
    iosBundleId: 'com.pamidoro.pamidoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7UQlnwcvSXFfSZemVWINdTkuqmeGUi8E',
    appId: '1:113425200543:web:d7184464101c240c50b9aa',
    messagingSenderId: '113425200543',
    projectId: 'pamidoro-app',
    authDomain: 'pamidoro-app.firebaseapp.com',
    storageBucket: 'pamidoro-app.firebasestorage.app',
    measurementId: 'G-HXJB8D92RZ',
  );
}
